baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = " 委内瑞拉 2019 0430 装甲车 压人 逐格播放 第 78 格开始 明显压人 "
theme = "hugo-theme-docdock"
#themesdir = "../.."
themesdir = "./themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false



[params]
editURL = ""
showVisitedLinks = true # default is false
## themeStyle = "flex" # "original" or "flex" # default "flex"
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = true # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = true # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
enableGitInfo = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


